"""empty message

Revision ID: 41477f59c866
Revises: 532bbcc09b84
Create Date: 2023-12-02 20:01:45.465878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41477f59c866'
down_revision = '532bbcc09b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.alter_column('author_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.alter_column('author_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
