"""empty message

Revision ID: 532bbcc09b84
Revises: 78ccbab306a6
Create Date: 2023-12-01 20:23:37.883140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532bbcc09b84'
down_revision = '78ccbab306a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add author_name as nullable
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.String(length=100), nullable=True))

    # Step 2: Update existing records
    op.execute("UPDATE quote SET author_name = 'Unknown' WHERE author_name IS NULL")

    # Step 3: Alter author_name to be non-nullable
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.alter_column('author_name', existing_type=sa.String(length=100), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quote', schema=None) as batch_op:
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###
